services:
  - type: web
    name: haven-backend
    env: node
    rootDir: Backend
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    plan: free
    envVars:
      # Set these in the Render dashboard (Environment tab)
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASS
        sync: false
      - key: PORT
        value: "5001"
